In [3]:
# Install pandasql
import subprocess
subprocess.run(['pip', 'install', 'pandasql'])

CompletedProcess(args=['pip', 'install', 'pandasql'], returncode=0)

In [4]:
import pandas as pd
from pandasql import sqldf
df = pd.read_csv(r"C:\Users\ASUS\DA Journey\train.csv")

pysql = lambda q: sqldf(q, globals())

print("dataset Loaded! shape :", df.shape)

dataset Loaded! shape : (891, 12)

In [5]:
result = pysql("SELECT * FROM df LIMIT 10")
result

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,None,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,None,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,None,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,None,C

In [6]:
result = pysql("""
select Sex ,COUNT(*) as train_passengers
FROM df 
GROUP BY Sex """)
result

      Sex  train_passengers
0  female               314
1    male               577

In [25]:
result = pysql("""
SELECT Name , Sex , Age , Pclass , Fare 
FROM df 
where Fare > 100 
ORDER BY Fare DESC 
LIMIT 10
""")
result

                                    Name     Sex   Age  Pclass      Fare
0                       Ward, Miss. Anna  female  35.0       1  512.3292
1     Cardeza, Mr. Thomas Drake Martinez    male  36.0       1  512.3292
2                 Lesurer, Mr. Gustave J    male  35.0       1  512.3292
3         Fortune, Mr. Charles Alexander    male  19.0       1  263.0000
4             Fortune, Miss. Mabel Helen  female  23.0       1  263.0000
5         Fortune, Miss. Alice Elizabeth  female  24.0       1  263.0000
6                      Fortune, Mr. Mark    male  64.0       1  263.0000
7             Ryerson, Miss. Emily Borie  female  18.0       1  262.3750
8  Ryerson, Miss. Susan Parker "Suzette"  female  21.0       1  262.3750
9               Baxter, Mr. Quigg Edmond    male  24.0       1  247.5208

In [31]:
result = pysql("""
SELECT Pclass , COUNT(*) as total_passengers,
ROUND(AVG(Fare),2) as avg_fare
FROM df 
GROUP BY Pclass
ORDER BY Pclass """)
result

   Pclass  total_passengers  avg_fare
0       1               216     84.15
1       2               184     20.66
2       3               491     13.68

In [7]:
result = pysql("""
SELECT Sex , Survived,
COUNT(*) as survivor_count
FROM df
GROUP BY Sex , Survived 
ORDER BY Sex """)
result

      Sex  Survived  survivor_count
0  female         0              81
1  female         1             233
2    male         0             468
3    male         1             109

In [11]:
result = pysql("""
SELECT Pclass, 
ROUND (avg(Age),2) as average_age
FROM df
GROUP BY Pclass
ORDER BY Pclass
""")
result

   Pclass  average_age
0       1        38.23
1       2        29.88
2       3        25.14

In [13]:
result = pysql("""
SELECT Pclass , COUNT(*) as survived_count 
from df
where Survived = 1
GROUP BY Pclass
""")
result

   Pclass  survived_count
0       1             136
1       2              87
2       3             119

In [15]:
result = pysql("""
Select Sex , 
Round (AVG(Fare) , 3) as Average_fare
from df
Group by Sex
Order by Sex 
""")
result

      Sex  Average_fare
0  female        44.480
1    male        25.524

In [21]:
result = pysql("""
SELECT Sex , COUNT(*) as passenger
from df 
GROUP BY Sex 
HAVING COUNT(*) > 400
""")
result

    Sex  passenger
0  male        577

In [31]:
import pandas as pd 
customers = pd.DataFrame({
    'Customer_ID': [1,2,3,4],
    'Name':['Rahul','Harsh','Tarique','Sahil']
        })
orders = pd.DataFrame({
    'Customer_ID': [1,2,2],
    'Product': ['Macbook','Asus','HP']
        })

In [32]:
customers

   Customer_ID     Name
0            1    Rahul
1            2    Harsh
2            3  Tarique
3            4    Sahil

In [33]:
orders

   Customer_ID  Product
0            1  Macbook
1            2     Asus
2            2       HP

In [31]:
result = pysql("""
select * from 
customers as c
LEFT JOIN orders as o
ON c.Customer_ID = o.Customer_ID
""")
result

PandaSQLException: (sqlite3.OperationalError) no such table: customers
[SQL:
select * from
customers as c
LEFT JOIN orders as o
ON c.Customer_ID = o.Customer_ID
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [32]:
import pandas as pd 
from pandasql import sqldf

df = pd.read_csv(r"C:\Users\ASUS\DA Journey\train.csv")

pysql = lambda q : sqldf(q, globals() )

print("dataset shape = ", df.shape)

dataset shape =  (891, 12)

In [28]:
result = pysql("""
Select Name , Fare , Pclass 
from df
where Fare > (SELECT AVG(Fare) from df)
order by Fare Desc
""")
result

                                                Name      Fare  Pclass
0                                   Ward, Miss. Anna  512.3292       1
1                 Cardeza, Mr. Thomas Drake Martinez  512.3292       1
2                             Lesurer, Mr. Gustave J  512.3292       1
3                     Fortune, Mr. Charles Alexander  263.0000       1
4                         Fortune, Miss. Mabel Helen  263.0000       1
..                                               ...       ...     ...
206                       Leitch, Miss. Jessie Wills   33.0000       2
207                Harper, Miss. Annie Jessie "Nina"   33.0000       2
208                                Harper, Rev. John   33.0000       2
209  Drew, Mrs. James Vivian (Lulu Thorne Christian)   32.5000       2
210                            Sutton, Mr. Frederick   32.3208       1

[211 rows x 3 columns]

In [27]:
print(df.columns.tolist())

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [26]:
result = pysql("""
SELECT Pclass , avg_fare 
from (
select Pclass, Round ( AVG(Fare) ,2) as avg_fare from df
group by Pclass)
where avg_fare >50 
""")
result

   Pclass  avg_fare
0       1     84.15

In [21]:
result = pysql("""
SELECT Name , Pclass , Fare 
FROM  df as outer_df 
where Fare > (SELECT  ROUND ( Avg(Fare), 2)from df 
as inner_df
WHERE inner_df.Pclass = outer_df.Pclass)

ORDER BY Pclass , Fare DESC 
""")
result

                                                  Name  Pclass      Fare
0                                     Ward, Miss. Anna       1  512.3292
1                   Cardeza, Mr. Thomas Drake Martinez       1  512.3292
2                               Lesurer, Mr. Gustave J       1  512.3292
3                       Fortune, Mr. Charles Alexander       1  263.0000
4                           Fortune, Miss. Mabel Helen       1  263.0000
..                                                 ...     ...       ...
293                              Barbara, Miss. Saiide       3   14.4542
294            Yasbeck, Mrs. Antoni (Selini Alexander)       3   14.4542
295  Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria ...       3   14.4000
296                          Danbom, Mr. Ernst Gilbert       3   14.4000
297                            Hansen, Mr. Claus Peter       3   14.1083

[298 rows x 3 columns]

In [39]:
df['rank_in_class'] = df. groupby('Pclass')['Fare'].rank(method ='first' ,ascending = False )
df[['Name' , 'Pclass' , 'Fare' , 'rank_in_class']].sort_values('rank_in_class') .head (10)

                                   Name  Pclass      Fare  rank_in_class
258                    Ward, Miss. Anna       1  512.3292            1.0
159          Sage, Master. Thomas Henry       3   69.5500            1.0
72                 Hood, Mr. Ambrose Jr       2   73.5000            1.0
679  Cardeza, Mr. Thomas Drake Martinez       1  512.3292            2.0
120         Hickman, Mr. Stanley George       2   73.5000            2.0
180        Sage, Miss. Constance Gladys       3   69.5500            2.0
737              Lesurer, Mr. Gustave J       1  512.3292            3.0
385           Davies, Mr. Charles Henry       2   73.5000            3.0
201                 Sage, Mr. Frederick       3   69.5500            3.0
27       Fortune, Mr. Charles Alexander       1  263.0000            4.0

In [43]:
df_sorted = df.sort_values('PassengerId') .copy()
df_sorted['running_total'] = df_sorted['Fare'].cumsum().round(2)
df_sorted[['PassengerId','Fare', 'running_total']].head(15)

    PassengerId     Fare  running_total
0             1   7.2500           7.25
1             2  71.2833          78.53
2             3   7.9250          86.46
3             4  53.1000         139.56
4             5   8.0500         147.61
5             6   8.4583         156.07
6             7  51.8625         207.93
7             8  21.0750         229.00
8             9  11.1333         240.14
9            10  30.0708         270.21
10           11  16.7000         286.91
11           12  26.5500         313.46
12           13   8.0500         321.51
13           14  31.2750         352.78
14           15   7.8542         360.64